import { z } from 'zod';

export const SECTION_ICONS = [
  { value: 'sparkles', label: 'Sparkles' },
  { value: 'briefcase', label: 'Briefcase' },
  { value: 'video', label: 'Video / Camera' },
  { value: 'wrench', label: 'Wrench / Tools' },
  { value: 'star', label: 'Star / Review' },
  { value: 'mail', label: 'Mail / Contact' },
  { value: 'rocket', label: 'Rocket / Venture' },
  { value: 'graduation-cap', label: 'Graduation Cap' },
  { value: 'layers', label: 'Layers / Projects' },
  { value: 'route', label: 'Route / Process' },
  { value: 'code', label: 'Code' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'shield', label: 'Shield / Security' },
  { value: 'flame', label: 'Flame / Hot' },
  { value: 'compass', label: 'Compass' },
  { value: 'cpu', label: 'CPU / Tech' },
  { value: 'globe', label: 'Globe' },
  { value: 'zap', label: 'Zap / Flash' },
  { value: 'trophy', label: 'Trophy' },
  { value: 'none', label: 'No Icon (Text Only)' },
] as const;

export type SectionIconName = (typeof SECTION_ICONS)[number]['value'];

export const BADGE_COLOR_PRESETS = [
  {
    name: 'Gold / Amber (Default)',
    textColor: 'var(--accent-gold-light)',
    bgColor: 'var(--accent-gold-bg)',
    borderColor: 'var(--accent-gold-border)',
    iconColor: 'var(--accent-gold)',
  },
  {
    name: 'Purple / Electric',
    textColor: 'var(--accent-purple-light)',
    bgColor: 'rgba(168, 85, 247, 0.1)',
    borderColor: 'rgba(168, 85, 247, 0.25)',
    iconColor: 'var(--accent-purple-light)',
  },
  {
    name: 'Emerald / Fintech',
    textColor: '#34d399',
    bgColor: 'rgba(16, 185, 129, 0.1)',
    borderColor: 'rgba(16, 185, 129, 0.25)',
    iconColor: '#10b981',
  },
  {
    name: 'Cyan / Modern Tech',
    textColor: '#38bdf8',
    bgColor: 'rgba(6, 182, 212, 0.1)',
    borderColor: 'rgba(6, 182, 212, 0.25)',
    iconColor: '#06b6d4',
  },
  {
    name: 'Rose / Creative',
    textColor: '#fb7185',
    bgColor: 'rgba(244, 63, 94, 0.1)',
    borderColor: 'rgba(244, 63, 94, 0.25)',
    iconColor: '#f43f5e',
  },
  {
    name: 'Silver / Slate',
    textColor: '#e2e8f0',
    bgColor: 'rgba(255, 255, 255, 0.06)',
    borderColor: 'rgba(255, 255, 255, 0.15)',
    iconColor: '#cbd5e1',
  },
];

export const landingSectionSchema = z.object({
  id: z.string().min(1, 'ID is required').max(60),
  title: z.string().min(1, 'Title is required').max(100),
  description: z.string().max(300).optional().default(''),
  kicker: z.string().max(100).optional().default(''),
  kicker_icon: z.string().max(60).optional().default('sparkles'),
  kicker_logo_url: z.string().max(500).optional().default(''),
  kicker_font_size: z.string().max(30).optional().default('0.75rem'),
  kicker_font_family: z.enum(['mono', 'sans', 'heading']).optional().default('mono'),
  kicker_font_weight: z.string().max(30).optional().default('600'),
  kicker_text_color: z.string().max(100).optional().default('var(--accent-gold-light)'),
  kicker_bg_color: z.string().max(100).optional().default('var(--accent-gold-bg)'),
  kicker_border_color: z.string().max(100).optional().default('var(--accent-gold-border)'),
  kicker_icon_color: z.string().max(100).optional().default('var(--accent-gold)'),
  kicker_letter_spacing: z.string().max(30).optional().default('0.08em'),
  kicker_text_transform: z.enum(['uppercase', 'capitalize', 'none']).optional().default('uppercase'),
  kicker_enabled: z.union([z.boolean(), z.number()]).transform((v) => (typeof v === 'boolean' ? (v ? 1 : 0) : v)).default(1),
  main_heading: z.string().max(300).optional().default(''),
  highlight_text: z.string().max(300).optional().default(''),
  subtitle: z.string().max(1000).optional().default(''),
  is_enabled: z.union([z.boolean(), z.number()]).transform((v) => (typeof v === 'boolean' ? (v ? 1 : 0) : v)).default(1),
  sort_order: z.coerce.number().int().default(0),
});

export type LandingSection = z.infer<typeof landingSectionSchema>;

export const DEFAULT_LANDING_SECTIONS: LandingSection[] = [
  {
    id: 'partners',
    title: 'Enterprise Clients & Brands',
    description: 'Header text above the client logos marquee and enterprise metrics ring.',
    kicker: 'TRUSTED BY',
    kicker_icon: 'shield',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Enterprise Clients &',
    highlight_text: 'Brands Worked With',
    subtitle: 'Government, enterprise, and high-growth teams call me when delivery cannot slip. I turn complex requirements into products that actually launch.',
    is_enabled: 1,
    sort_order: 0,
  },
  {
    id: 'cases',
    title: 'Featured Case Studies',
    description: 'Header text above the interactive case studies slider and proof matrix.',
    kicker: 'FEATURED WORK',
    kicker_icon: 'sparkles',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Case Studies &',
    highlight_text: 'Real Results',
    subtitle: 'Measurable outcomes delivered for enterprise platforms, B2B marketplaces, and venture-backed scale-ups.',
    is_enabled: 1,
    sort_order: 1,
  },
  {
    id: 'about',
    title: 'About Me Intro Paragraph',
    description: 'Optional introductory narrative section directly following Case Studies.',
    kicker: 'ABOUT',
    kicker_icon: 'sparkles',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'About Me',
    highlight_text: '',
    subtitle: '',
    is_enabled: 1,
    sort_order: 2,
  },
  {
    id: 'process',
    title: 'How I Work (4-Phase Process)',
    description: 'Header text above the 4 delivery phases: Discover, Define, Execute, Optimize.',
    kicker: 'HOW I WORK',
    kicker_icon: 'route',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'From idea to',
    highlight_text: 'shipped product.',
    subtitle: 'A simple, repeatable path: understand, design, build, and improve.',
    is_enabled: 1,
    sort_order: 3,
  },
  {
    id: 'videos',
    title: 'PM Talks & Video Breakdowns',
    description: 'Header text above the video podcast episodes and breakdown carousel.',
    kicker: 'PM TALKS & BREAKDOWNS',
    kicker_icon: 'video',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Insights on',
    highlight_text: 'product management',
    subtitle: 'Weekly short videos on how I plan, prioritise, and ship real products.',
    is_enabled: 1,
    sort_order: 4,
  },
  {
    id: 'toolkit',
    title: 'Technical Toolkit & Skills',
    description: 'Header text above the software tools, methodologies, and technical stack badges.',
    kicker: 'TECHNICAL TOOLKIT',
    kicker_icon: 'wrench',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Tools, stack &',
    highlight_text: 'methodologies',
    subtitle: 'The engineering, product, and leadership stack behind the delivery.',
    is_enabled: 1,
    sort_order: 5,
  },
  {
    id: 'history',
    title: 'Career Experience & Timeline',
    description: 'Header text above the career timeline, education, and professional certifications.',
    kicker: 'CAREER MATRIX',
    kicker_icon: 'briefcase',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Experience &',
    highlight_text: 'Credentials',
    subtitle: 'Tenure across enterprise platforms, scale-ups, and academic qualifications.',
    is_enabled: 1,
    sort_order: 6,
  },
  {
    id: 'other_projects',
    title: 'Other Projects & Builds',
    description: 'Header text above shorter builds, client projects, and advisory engagements.',
    kicker: 'OTHER PROJECTS',
    kicker_icon: 'layers',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Shorter builds &',
    highlight_text: 'engagements',
    subtitle: 'Work outside the main timeline — products I helped scope, ship or steady.',
    is_enabled: 1,
    sort_order: 7,
  },
  {
    id: 'testimonials',
    title: 'Testimonials & Social Proof',
    description: 'Header text above leadership endorsements and client feedback.',
    kicker: 'ENDORSEMENTS',
    kicker_icon: 'star',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Recommendations &',
    highlight_text: 'Social Proof',
    subtitle: 'Feedback from executive stakeholders, engineering directors, and founders.',
    is_enabled: 1,
    sort_order: 8,
  },
  {
    id: 'contact',
    title: 'Direct Inquiries & Contact',
    description: 'Header text above consultation booking and direct contact channels.',
    kicker: 'DIRECT INQUIRIES',
    kicker_icon: 'mail',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-purple-light)',
    kicker_bg_color: 'rgba(168, 85, 247, 0.08)',
    kicker_border_color: 'rgba(168, 85, 247, 0.25)',
    kicker_icon_color: 'var(--accent-purple-light)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: "Let's build",
    highlight_text: 'something great.',
    subtitle: 'Open to select technical product consulting, fractional delivery leadership, and high-impact advisory.',
    is_enabled: 1,
    sort_order: 9,
  },
  {
    id: 'ventures',
    title: 'Outside Client Work (Ventures)',
    description: 'Header text above personal software ventures and side businesses.',
    kicker: 'SIDE VENTURES',
    kicker_icon: 'rocket',
    kicker_logo_url: '',
    kicker_font_size: '0.75rem',
    kicker_font_family: 'mono',
    kicker_font_weight: '600',
    kicker_text_color: 'var(--accent-gold-light)',
    kicker_bg_color: 'var(--accent-gold-bg)',
    kicker_border_color: 'var(--accent-gold-border)',
    kicker_icon_color: 'var(--accent-gold)',
    kicker_letter_spacing: '0.08em',
    kicker_text_transform: 'uppercase',
    kicker_enabled: 1,
    main_heading: 'Outside',
    highlight_text: 'Client Work',
    subtitle: 'The ventures I build and run on my own time.',
    is_enabled: 1,
    sort_order: 10,
  },
];
