/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAboutRouteImport } from './routes/admin/about'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminBrandingRouteImport } from './routes/admin/branding'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminCredentialsRouteImport } from './routes/admin/credentials'
import { Route as AdminExperienceRouteImport } from './routes/admin/experience'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminToolkitRouteImport } from './routes/admin/toolkit'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminInsightsIndexRouteImport } from './routes/admin/insights/index'
import { Route as AdminInsightsNewRouteImport } from './routes/admin/insights/new'
import { Route as AdminContentTypeIndexRouteImport } from './routes/admin/content/$type/index'
import { Route as AdminContentTypeNewRouteImport } from './routes/admin/content/$type/new'
import { Route as AdminInsightsIdEditRouteImport } from './routes/admin/insights/$id.edit'
import { Route as AdminContentTypeIdEditRouteImport } from './routes/admin/content/$type/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCredentialsRoute = AdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExperienceRoute = AdminExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminToolkitRoute = AdminToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInsightsIndexRoute = AdminInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInsightsNewRoute = AdminInsightsNewRouteImport.update({
  id: '/insights/new',
  path: '/insights/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentTypeIndexRoute = AdminContentTypeIndexRouteImport.update({
  id: '/content/$type/',
  path: '/content/$type/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentTypeNewRoute = AdminContentTypeNewRouteImport.update({
  id: '/content/$type/new',
  path: '/content/$type/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInsightsIdEditRoute = AdminInsightsIdEditRouteImport.update({
  id: '/insights/$id/edit',
  path: '/insights/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentTypeIdEditRoute = AdminContentTypeIdEditRouteImport.update({
  id: '/content/$type/$id/edit',
  path: '/content/$type/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/toolkit': typeof AdminToolkitRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/admin/content/$type/new': typeof AdminContentTypeNewRoute
  '/admin/insights/$id/edit': typeof AdminInsightsIdEditRoute
  '/admin/content/$type/': typeof AdminContentTypeIndexRoute
  '/admin/content/$type/$id/edit': typeof AdminContentTypeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/toolkit': typeof AdminToolkitRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/admin/insights': typeof AdminInsightsIndexRoute
  '/admin/content/$type/new': typeof AdminContentTypeNewRoute
  '/admin/insights/$id/edit': typeof AdminInsightsIdEditRoute
  '/admin/content/$type': typeof AdminContentTypeIndexRoute
  '/admin/content/$type/$id/edit': typeof AdminContentTypeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/credentials': typeof AdminCredentialsRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/toolkit': typeof AdminToolkitRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/insights/new': typeof AdminInsightsNewRoute
  '/admin/insights/': typeof AdminInsightsIndexRoute
  '/admin/content/$type/new': typeof AdminContentTypeNewRoute
  '/admin/insights/$id/edit': typeof AdminInsightsIdEditRoute
  '/admin/content/$type/': typeof AdminContentTypeIndexRoute
  '/admin/content/$type/$id/edit': typeof AdminContentTypeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/about'
    | '/admin/activity'
    | '/admin/branding'
    | '/admin/clients'
    | '/admin/credentials'
    | '/admin/experience'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/toolkit'
    | '/admin/users'
    | '/admin/'
    | '/admin/insights/new'
    | '/admin/insights/'
    | '/admin/content/$type/new'
    | '/admin/insights/$id/edit'
    | '/admin/content/$type/'
    | '/admin/content/$type/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/about'
    | '/admin/activity'
    | '/admin/branding'
    | '/admin/clients'
    | '/admin/credentials'
    | '/admin/experience'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/toolkit'
    | '/admin/users'
    | '/admin'
    | '/admin/insights/new'
    | '/admin/insights'
    | '/admin/content/$type/new'
    | '/admin/insights/$id/edit'
    | '/admin/content/$type'
    | '/admin/content/$type/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/about'
    | '/admin/activity'
    | '/admin/branding'
    | '/admin/clients'
    | '/admin/credentials'
    | '/admin/experience'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/toolkit'
    | '/admin/users'
    | '/admin/'
    | '/admin/insights/new'
    | '/admin/insights/'
    | '/admin/content/$type/new'
    | '/admin/insights/$id/edit'
    | '/admin/content/$type/'
    | '/admin/content/$type/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/credentials': {
      id: '/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AdminCredentialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/experience': {
      id: '/admin/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/toolkit': {
      id: '/admin/toolkit'
      path: '/toolkit'
      fullPath: '/admin/toolkit'
      preLoaderRoute: typeof AdminToolkitRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/insights/': {
      id: '/admin/insights/'
      path: '/insights'
      fullPath: '/admin/insights/'
      preLoaderRoute: typeof AdminInsightsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/insights/new': {
      id: '/admin/insights/new'
      path: '/insights/new'
      fullPath: '/admin/insights/new'
      preLoaderRoute: typeof AdminInsightsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/$type/': {
      id: '/admin/content/$type/'
      path: '/content/$type'
      fullPath: '/admin/content/$type/'
      preLoaderRoute: typeof AdminContentTypeIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/$type/new': {
      id: '/admin/content/$type/new'
      path: '/content/$type/new'
      fullPath: '/admin/content/$type/new'
      preLoaderRoute: typeof AdminContentTypeNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/insights/$id/edit': {
      id: '/admin/insights/$id/edit'
      path: '/insights/$id/edit'
      fullPath: '/admin/insights/$id/edit'
      preLoaderRoute: typeof AdminInsightsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content/$type/$id/edit': {
      id: '/admin/content/$type/$id/edit'
      path: '/content/$type/$id/edit'
      fullPath: '/admin/content/$type/$id/edit'
      preLoaderRoute: typeof AdminContentTypeIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCredentialsRoute: typeof AdminCredentialsRoute
  AdminExperienceRoute: typeof AdminExperienceRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminToolkitRoute: typeof AdminToolkitRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInsightsNewRoute: typeof AdminInsightsNewRoute
  AdminInsightsIndexRoute: typeof AdminInsightsIndexRoute
  AdminContentTypeNewRoute: typeof AdminContentTypeNewRoute
  AdminInsightsIdEditRoute: typeof AdminInsightsIdEditRoute
  AdminContentTypeIndexRoute: typeof AdminContentTypeIndexRoute
  AdminContentTypeIdEditRoute: typeof AdminContentTypeIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCredentialsRoute: AdminCredentialsRoute,
  AdminExperienceRoute: AdminExperienceRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminToolkitRoute: AdminToolkitRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInsightsNewRoute: AdminInsightsNewRoute,
  AdminInsightsIndexRoute: AdminInsightsIndexRoute,
  AdminContentTypeNewRoute: AdminContentTypeNewRoute,
  AdminInsightsIdEditRoute: AdminInsightsIdEditRoute,
  AdminContentTypeIndexRoute: AdminContentTypeIndexRoute,
  AdminContentTypeIdEditRoute: AdminContentTypeIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
